// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjsxUg7aoS6kUNHcfK1kbH5PRqvXZZ-U',
    appId: '1:813549852839:web:ac4b660384191585af6382',
    messagingSenderId: '813549852839',
    projectId: 'masjid-at-taufiq',
    authDomain: 'masjid-at-taufiq.firebaseapp.com',
    storageBucket: 'masjid-at-taufiq.firebasestorage.app',
    measurementId: 'G-MMQ3DPX4QT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeicENc0BubehwIQsWjvuqgt4j5SICADo',
    appId: '1:813549852839:ios:f395ad02eb1fe56daf6382',
    messagingSenderId: '813549852839',
    projectId: 'masjid-at-taufiq',
    storageBucket: 'masjid-at-taufiq.firebasestorage.app',
    iosBundleId: 'com.example.masjidBerhasil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOjsxUg7aoS6kUNHcfK1kbH5PRqvXZZ-U',
    appId: '1:813549852839:web:6b0ef1497f0987dbaf6382',
    messagingSenderId: '813549852839',
    projectId: 'masjid-at-taufiq',
    authDomain: 'masjid-at-taufiq.firebaseapp.com',
    storageBucket: 'masjid-at-taufiq.firebasestorage.app',
    measurementId: 'G-831R76B8HK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeicENc0BubehwIQsWjvuqgt4j5SICADo',
    appId: '1:813549852839:ios:f395ad02eb1fe56daf6382',
    messagingSenderId: '813549852839',
    projectId: 'masjid-at-taufiq',
    storageBucket: 'masjid-at-taufiq.firebasestorage.app',
    iosBundleId: 'com.example.masjidBerhasil',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0VkvIxg5Fa0Fz9fJwWgBY0-UJ2fFkccw',
    appId: '1:813549852839:android:8e32b39b5861e2a1af6382',
    messagingSenderId: '813549852839',
    projectId: 'masjid-at-taufiq',
    storageBucket: 'masjid-at-taufiq.firebasestorage.app',
  );

}